name: "🐞 Bug report"
description: Report a problem or bug you found in the supplementary style guide.
labels: [bug]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the impact of this bug?
      options:
        - Critical (blocks usage or causes data loss)
        - Major (significant impact, but workaround exists)
        - Minor (cosmetic or small impact)
        - Trivial (no real impact)
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgently should this be fixed?
      options:
        - P1 (highest)
        - P2
        - P3 (lowest)
    validations:
      required: true
  - type: input
    id: affected-pages
    attributes:
      label: Affected page(s)
      description: Please provide a link (or links) to the page(s) where you found the bug.
      placeholder: "https://github.com/redhat-documentation/supplementary-style-guide/path/to/page"
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: What went wrong? Be as specific as possible.
      placeholder: "A clear and concise description of the bug."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: textarea
    id: proposed-change
    attributes:
      label: Describe the proposed change
      description: What change do you recommend to resolve or improve this issue?
      placeholder: "Describe your proposed change here."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        **Optional next step:**
        After submitting this issue, you can help resolve it by [opening a pull request](https://github.com/redhat-documentation/supplementary-style-guide/compare) that references this issue.
